### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by OutOfBears** [jesterret/DBDPakTrack#1]
Sorry for dropping an issue like this, but I was wondering if you have any sort of discord, etc that I can contact you on.

**Comment by jesterret** [comment]
Haha no problem. Sorry for later response! (probably should've had the repository watched so I get emails...)
I don't really use discord all that often, but it would be jesterret#3049, but better bet would be my [steam](https://steamcommunity.com/id/jesterret).
