### ISSUE TITLE
How do you do this?

### ISSUE THREAD

**Issue by samcaulfield** [jesterret/DBDPakTrack#2]
Hi there,

I'm thinking of building a website for Dead by Daylight and I'd like to be able to parse some of the game's DataTables automatically (for stuff like perks and addons). I was just wondering, how you are able to recover the plaintext versions of the .uasset files such as [this one](https://github.com/jesterret/DBDPakTrack/blob/master/DeadByDaylight/Content/Data/PerkDB.uasset)?

I'm not an Unreal Engine user, I just want to be able to reliably and easily extract some of the textual data (like perk descriptions) from the game files. So far, I've used various tools (e.g. UnrealPak) to extract the game's .pak files, but the .uassets aren't in a plaintext state after I do that.

Thanks!

**Comment by OutOfBears** [comment]
Hello! Jesterret has made a tool in C# to parse the Pak files which lets you get the exports of uassets, which I've implemented in my API to let me get the PerkDB, you can find an it [here](https://github.com/Nexure/DBD-API/blob/master/DBD-API/Services/SteamDepotService.cs#L126) (shameless advertising lol)

You can find the unreal tools repo [here](https://github.com/UnrealTools/UnrealTools)

**Comment by samcaulfield** [comment]
That's really helpful, thanks for the information Nexure! By the way, your dbd-stats site is really cool.
